### ISSUE TITLE
Feature request: Test formatting improvement

### ISSUE THREAD

**Issue by tuzz** [computationclub/vm-translator#1]
I was thinking a nice improvement might be to add some custom formatting to the test output. When our test output includes RAM addresses 0, 1, 2, 3 or 4, we could reference SP, LCL, ARG, THIS and THAT respectively. I'm terrible at reading RSpec's string diffs and it's hard to remember the order of things. Perhaps this is moot now that we've (almost) passed this chapter?

**Comment by tomstuart** [comment]
Quitter.
